### ISSUE TITLE
AttributeError: 'Options' object has no attribute 'get_all_related_objects'

### ISSUE THREAD

**Issue by bashu** [ixc/django-model-settings#16]
Using django 1.10+

```python
Traceback (most recent call last):
  ...
  File "/Users/bashu/Projects/django-model-settings/model_settings/models.py", line 38, in create
    model = Setting.get_model_for_value(value)
  File "/Users/bashu/Projects/django-model-settings/model_settings/models.py", line 74, in get_model_for_value
    for related_object in cls._meta.get_all_related_objects():
AttributeError: 'Options' object has no attribute 'get_all_related_objects'
```

**Comment by bashu** [comment]
Hey, @Aramgutang @cogat @markfinger 

We are using `django-model-settings` in production and it would be cool to see this bug fixed
